import { existsSync } from "node:fs";
import {
    SPEEDTEST_BIN_FILEPATH,
    SQLITE_DATABASE_PATH,
} from "./config/environment";

if (!existsSync(SPEEDTEST_BIN_FILEPATH)) {
    console.error("speedtest binary not found");
    process.exit(2);
}

if (!existsSync(SQLITE_DATABASE_PATH)) {
    console.error("database.sql not found, it'll be autogenerated");
}
